const BANK_ICON_BASE = "https://henriquezolini.github.io/react-bancos/icons";

const SPECIAL_LOGOS: Array<[RegExp, string]> = [
  [/nubank.*ultravioleta/i, `${BANK_ICON_BASE}/nubankultravioleta.svg`],
  [/nubank.*croma/i, `${BANK_ICON_BASE}/nubankcroma.svg`],
  [/c6.*carbon/i, `${BANK_ICON_BASE}/c6carbon.svg`],
  [/(itaú|itau).*personnalit.*the one/i, `${BANK_ICON_BASE}/itautheone.svg`],
  [/(itaú|itau).*personnalit/i, `${BANK_ICON_BASE}/itaupersonnalite.svg`],
  [/(itaú|itau).*uniclass/i, `${BANK_ICON_BASE}/itauuniclass.svg`],
  [/(itaú|itau).*black/i, `${BANK_ICON_BASE}/itaublack.svg`],
  [/santander.*unique/i, `${BANK_ICON_BASE}/santanderunique.svg`],
  [/santander.*elite/i, `${BANK_ICON_BASE}/santanderelite.svg`],
  [/bradesco.*infinite/i, `${BANK_ICON_BASE}/bradescoinfinite.svg`],
  [/(banco do brasil|ourocard).*infinite/i, `${BANK_ICON_BASE}/bancodobrasilinfinite.svg`],
  [/sicredi.*infinite/i, `${BANK_ICON_BASE}/sicrediinfinite.svg`],
  [/banrisul.*infinite/i, `${BANK_ICON_BASE}/banrisulinfinite.svg`],
  [/safra.*infinite/i, `${BANK_ICON_BASE}/safrainfiniteiridium.svg`],
  [/btg.*ultrablue/i, `${BANK_ICON_BASE}/btgultrablue.svg`],
  [/picpay.*black/i, `${BANK_ICON_BASE}/picpayblack.svg`],
  [/original.*black/i, `${BANK_ICON_BASE}/originalblack.svg`],
  [/original.*gold/i, `${BANK_ICON_BASE}/originalgold.svg`],
  [/original.*platinum/i, `${BANK_ICON_BASE}/originalplatinum.svg`],
  [/original.*international/i, `${BANK_ICON_BASE}/originalinternational.svg`],
];

const INSTITUTION_LOGOS: Array<[RegExp, string]> = [
  [/(porto bank|porto seguro)/i, "https://companieslogo.com/img/orig/PSSA3.SA-0314a40c.svg"],
  [/mercado pago/i, "https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/mercado-pago/default.svg"],
  [/(banco do brasil|ourocard)/i, `${BANK_ICON_BASE}/bancodobrasil.svg`],
  [/bradesco/i, `${BANK_ICON_BASE}/bradesco.svg`],
  [/caixa/i, `${BANK_ICON_BASE}/caixa.svg`],
  [/nubank/i, `${BANK_ICON_BASE}/nubank.svg`],
  [/(itaú|itau)/i, `${BANK_ICON_BASE}/itau.svg`],
  [/santander/i, `${BANK_ICON_BASE}/santander.svg`],
  [/(banco inter|\binter\b)/i, `${BANK_ICON_BASE}/inter.svg`],
  [/\bc6\b/i, `${BANK_ICON_BASE}/c6bank.svg`],
  [/btg/i, `${BANK_ICON_BASE}/btgpactual.svg`],
  [/\bxp\b/i, `${BANK_ICON_BASE}/xp.svg`],
  [/sicoob/i, `${BANK_ICON_BASE}/sicoob.svg`],
  [/sicredi/i, `${BANK_ICON_BASE}/sicredi.svg`],
  [/banrisul/i, `${BANK_ICON_BASE}/banrisul.svg`],
  [/safra/i, `${BANK_ICON_BASE}/safra.svg`],
  [/(banco bv|\bbv\b)/i, `${BANK_ICON_BASE}/bv.svg`],
  [/(banco pan|\bpan\b)/i, `${BANK_ICON_BASE}/pan.svg`],
  [/bmg/i, `${BANK_ICON_BASE}/bmg.svg`],
  [/original/i, `${BANK_ICON_BASE}/original.svg`],
  [/neon/i, `${BANK_ICON_BASE}/neon.svg`],
  [/cora/i, `${BANK_ICON_BASE}/cora.svg`],
  [/picpay/i, `${BANK_ICON_BASE}/picpay.svg`],
  [/(pagbank|pagseguro)/i, `${BANK_ICON_BASE}/pagbank.svg`],
  [/stone/i, `${BANK_ICON_BASE}/stone.svg`],
  [/daycoval/i, `${BANK_ICON_BASE}/daycoval.svg`],
  [/(\bbrb\b|banco de brasília|banco de brasilia)/i, `${BANK_ICON_BASE}/brb.svg`],
  [/banco do nordeste/i, `${BANK_ICON_BASE}/bancodonordeste.svg`],
  [/(banco da amazônia|banco da amazonia)/i, `${BANK_ICON_BASE}/bancodaamazonia.svg`],
  [/banestes/i, `${BANK_ICON_BASE}/banestes.svg`],
  [/mercantil/i, `${BANK_ICON_BASE}/mercantil.svg`],
  [/agibank/i, `${BANK_ICON_BASE}/agibank.svg`],
  [/(will bank|willbank)/i, `${BANK_ICON_BASE}/willbank.svg`],
  [/sofisa/i, `${BANK_ICON_BASE}/sofisa.svg`],
  [/abc brasil/i, `${BANK_ICON_BASE}/abcbrasil.svg`],
  [/(citibank|citi bank)/i, `${BANK_ICON_BASE}/citibank.svg`],
  [/\barbi\b/i, `${BANK_ICON_BASE}/arbi.svg`],
  [/banese/i, `${BANK_ICON_BASE}/banese.svg`],
  [/bnp paribas/i, `${BANK_ICON_BASE}/bnpparibas.svg`],
  [/bs2/i, `${BANK_ICON_BASE}/bs2.svg`],
  [/warren/i, `${BANK_ICON_BASE}/warren.svg`],
  [/toro/i, `${BANK_ICON_BASE}/toro.svg`],
  [/ailos/i, `${BANK_ICON_BASE}/ailos.svg`],
  [/avenue/i, `${BANK_ICON_BASE}/avenue.svg`],
  [/(bank of america|merrill lynch)/i, `${BANK_ICON_BASE}/bankofamerica.svg`],
  [/(banpará|banpara)/i, `${BANK_ICON_BASE}/banpara.svg`],
  [/conta simples/i, `${BANK_ICON_BASE}/contasimples.svg`],
  [/ifood pago/i, `${BANK_ICON_BASE}/ifoodpago.svg`],
  [/(magalupay|magalu pay)/i, `${BANK_ICON_BASE}/magalupay.svg`],
  [/flash/i, `${BANK_ICON_BASE}/flash.svg`],
  [/alelo/i, `${BANK_ICON_BASE}/alelo.svg`],
  [/wise/i, `${BANK_ICON_BASE}/wise.svg`],
  [/nomad/i, `${BANK_ICON_BASE}/nomad.svg`],
  [/revolut/i, `${BANK_ICON_BASE}/revolut.svg`],
];

export function inferCardInstitutionLogoUrl(name?: string | null): string | null {
  if (!name) return null;
  for (const [pattern, url] of SPECIAL_LOGOS) if (pattern.test(name)) return url;
  for (const [pattern, url] of INSTITUTION_LOGOS) if (pattern.test(name)) return url;
  return null;
}
