from pathlib import Path

def r(p,o,n,l):
 s=Path(p).read_text()
 if n in s: print(l,'already'); return
 if o not in s: raise SystemExit(l+' anchor not found')
 Path(p).write_text(s.replace(o,n,1)); print(l,'ok')
r('src/components/QuickAddTransactionDialog.tsx','import { buildTransferTransactionNames, extractTransferDescription } from "@/lib/transfer-label";','import { buildTransferTransactionNames, extractTransferDescription } from "@/lib/transfer-label";\nimport type { VoiceTransactionDraft } from "@/lib/voice-transaction";','quickadd import')
r('src/components/QuickAddTransactionDialog.tsx','  /** Pré-seleciona a data. Exibição canônica: "dd-MM-yyyy"; formatos legados também são aceitos. */\n  initialDate?: string;\n  onSuccess?: () => void;','  /** Pré-seleciona a data. Exibição canônica: "dd-MM-yyyy"; formatos legados também são aceitos. */\n  initialDate?: string;\n  /** Rascunho preenchido pelo lançamento por voz. Sempre exige revisão e confirmação do usuário. */\n  initialDraft?: VoiceTransactionDraft | null;\n  onSuccess?: () => void;','quickadd props')
r('src/components/QuickAddTransactionDialog.tsx','export function QuickAddTransactionDialog({ open, onOpenChange, initialType = "expense", initialCardName, initialDate, onSuccess, copyData }: Props) {','export function QuickAddTransactionDialog({ open, onOpenChange, initialType = "expense", initialCardName, initialDate, initialDraft, onSuccess, copyData }: Props) {','quickadd signature')
r('src/components/QuickAddTransactionDialog.tsx','    const prefs = !copyData && initialType !== "income" && initialType !== "transfer" ? readPrefs() : null;\n    setInstallmentEnabled(prefs?.enabled ?? false);\n    setInstallmentCount(prefs?.count ?? 2);\n    setInstallmentStart(1);\n    setInstallmentMode(prefs?.mode ?? "divide");','    const voiceInstallments = initialDraft?.installmentCount && initialDraft.installmentCount >= 2\n      ? initialDraft.installmentCount\n      : null;\n    const prefs = !initialDraft && !copyData && initialType !== "income" && initialType !== "transfer" ? readPrefs() : null;\n    setInstallmentEnabled(voiceInstallments ? true : (prefs?.enabled ?? false));\n    setInstallmentCount(voiceInstallments ?? prefs?.count ?? 2);\n    setInstallmentStart(1);\n    setInstallmentMode("divide");','quickadd installments')
r('src/components/QuickAddTransactionDialog.tsx','    setNewTx({\n      icon: copyData ? copyData.icon : (initialType === "income" ? "💰" : "🍔"),\n      name: copyData ? copyData.name : "",\n      category: copyData ? copyData.category : (initialType === "income" ? "Renda > Salário" : "Alimentação > Outros"),\n      date: normalizeQuickAddDate(initialDate),\n      amount: 0,\n      type: copyData ? (copyData.category.startsWith("Receita") || (copyData.category !== "Transferência" && !copyData.category.startsWith("Transferências") && !copyData.category.startsWith("Alimentação") && initialType === "income") ? "income" : "expense") : (initialType === "income" ? "income" : "expense"),\n      card: copyData ? copyData.card : null,\n      bank_account_id: copyData ? copyData.bank_account_id : null,\n    });','    setNewTx({\n      icon: initialDraft?.icon || (copyData ? copyData.icon : (initialType === "income" ? "💰" : "🍔")),\n      name: initialDraft?.name || (copyData ? copyData.name : ""),\n      category: initialDraft?.category || (copyData ? copyData.category : (initialType === "income" ? "Renda > Salário" : "Alimentação > Outros")),\n      date: normalizeQuickAddDate(initialDraft?.date || initialDate),\n      amount: initialDraft?.amount || 0,\n      type: initialDraft?.type || (copyData ? (copyData.category.startsWith("Receita") || (copyData.category !== "Transferência" && !copyData.category.startsWith("Transferências") && !copyData.category.startsWith("Alimentação") && initialType === "income") ? "income" : "expense") : (initialType === "income" ? "income" : "expense")),\n      card: initialDraft?.card ?? (copyData ? copyData.card : null),\n      bank_account_id: copyData ? copyData.bank_account_id : null,\n    });','quickadd newtx')
r('src/components/QuickAddTransactionDialog.tsx','  }, [open, initialType, initialDate, fetchData, fetchHistory]);','  }, [open, initialType, initialDate, initialDraft, fetchData, fetchHistory]);','quickadd deps')
r('src/components/QuickAddTransactionDialog.tsx','  // Persistir preferências de parcelamento ao alterar.\n  useEffect(() => {','  useEffect(() => {\n    if (!open || !initialDraft?.name || txHistory.size === 0) return;\n    const history = txHistory.get(initialDraft.name.trim().toLowerCase());\n    if (!history) return;\n    setNewTx(prev => ({ ...prev, icon: history.icon, category: history.category }));\n  }, [open, initialDraft?.name, txHistory]);\n\n  useEffect(() => {\n    if (!open || !initialDraft?.card || cardOptions.length === 0) return;\n    const spoken = initialDraft.card.trim().toLowerCase();\n    const match = cardOptions.find(card => card.name.trim().toLowerCase() === spoken);\n    if (!match || newTx.card === match.name) return;\n    setNewTx(prev => ({ ...prev, card: match.name, bank_account_id: null }));\n  }, [open, initialDraft?.card, cardOptions, newTx.card]);\n\n  // Persistir preferências de parcelamento ao alterar.\n  useEffect(() => {','quickadd reconciliation')
r('src/routes/home.tsx','import { ThemeToggle } from "@/components/ThemeToggle";','import { ThemeToggle } from "@/components/ThemeToggle";\nimport { VoiceTransactionButton } from "@/components/VoiceTransactionButton";\nimport { QuickAddTransactionDialog } from "@/components/QuickAddTransactionDialog";\nimport type { VoiceTransactionDraft } from "@/lib/voice-transaction";','home imports')
r('src/routes/home.tsx','  const [loading, setLoading] = useState(true);\n  const [selectedMonth, setSelectedMonth] = useState<Date>(() => {','  const [loading, setLoading] = useState(true);\n  const [voiceDraft, setVoiceDraft] = useState<VoiceTransactionDraft | null>(null);\n  const [voiceDialogOpen, setVoiceDialogOpen] = useState(false);\n  const [selectedMonth, setSelectedMonth] = useState<Date>(() => {','home state')
r('src/routes/home.tsx','          <Link to="/transactions" search={{ action: "add" } as any} className="flex h-9 w-9 items-center justify-center rounded-full bg-primary text-primary-foreground" aria-label="Adicionar transação">\n            <Plus className="h-4 w-4" />\n          </Link>','          <VoiceTransactionButton\n            onDraft={(draft) => {\n              setVoiceDraft(draft);\n              setVoiceDialogOpen(true);\n            }}\n          />\n          <Link to="/transactions" search={{ action: "add" } as any} className="flex h-9 w-9 items-center justify-center rounded-full bg-primary text-primary-foreground" aria-label="Adicionar transação">\n            <Plus className="h-4 w-4" />\n          </Link>','home mic')
r('src/routes/home.tsx','      {reminders.length > 0 && (\n        <section>','      <QuickAddTransactionDialog\n        open={voiceDialogOpen}\n        onOpenChange={(open) => {\n          setVoiceDialogOpen(open);\n          if (!open) setVoiceDraft(null);\n        }}\n        initialType={voiceDraft?.type || "expense"}\n        initialDraft={voiceDraft}\n        onSuccess={() => window.location.reload()}\n      />\n\n      {reminders.length > 0 && (\n        <section>','home dialog')
