from pathlib import Path

p = Path('src/routes/cards.tsx')
s = p.read_text()

state_anchor = '''  const [showEditDialog, setShowEditDialog] = useState(false);\n  const [editTx, setEditTx] = useState<CardTransaction | null>(null);\n'''
state_repl = '''  const [showEditDialog, setShowEditDialog] = useState(false);\n  const [editTx, setEditTx] = useState<CardTransaction | null>(null);\n  const [editOriginalTx, setEditOriginalTx] = useState<CardTransaction | null>(null);\n  const [editScopeDialogOpen, setEditScopeDialogOpen] = useState(false);\n'''
if state_anchor not in s:
    raise SystemExit('state anchor not found')
s = s.replace(state_anchor, state_repl, 1)

old = '''  const handleEditTx = (tx: CardTransaction) => {\n    setEditTx({ ...tx });\n    setShowEditDialog(true);\n  };\n\n  const saveEditTx = async () => {\n    if (!editTx) return;\n    setIsSavingEdit(true);\n    try {\n      const { error } = await supabase\n        .from("transactions")\n        .update({\n          name: editTx.name,\n          category: editTx.category,\n          icon: editTx.icon,\n          date: editTx.date,\n          amount: editTx.amount,\n        })\n        .eq("id", editTx.id);\n      \n      if (error) throw error;\n      \n      toast.success("Transação atualizada com sucesso");\n      setShowEditDialog(false);\n      // Refresh transactions for the card\n      // Refresh transactions silently — preserves scroll and active period.\n      if (invoiceCard) refreshInvoiceSilently(invoiceCard);\n      else fetchAll();\n\n    } catch (error: any) {\n      console.error("Error updating transaction:", error);\n      toast.error("Erro ao atualizar transação");\n    } finally {\n      setIsSavingEdit(false);\n    }\n  };\n'''
new = '''  const handleEditTx = (tx: CardTransaction) => {\n    setEditOriginalTx({ ...tx });\n    setEditTx({ ...tx });\n    setEditScopeDialogOpen(false);\n    setShowEditDialog(true);\n  };\n\n  const performSaveEditTx = async (scope: "single" | "future") => {\n    if (!editTx) return;\n    setIsSavingEdit(true);\n    try {\n      const current = Math.max(1, Number(editTx.installment_number) || 1);\n      const baseName = stripInstallmentSuffix(editTx.name);\n      const sharedUpdate = {\n        name: baseName,\n        category: editTx.category,\n        icon: editTx.icon,\n        amount: editTx.amount,\n      };\n\n      if (scope === "future" && editTx.installment_group_id) {\n        const { data: siblings, error: siblingsError } = await supabase\n          .from("transactions")\n          .select("id, installment_number")\n          .eq("installment_group_id", editTx.installment_group_id)\n          .gte("installment_number", current)\n          .order("installment_number", { ascending: true });\n        if (siblingsError) throw siblingsError;\n\n        const dateChanged = !!editOriginalTx && editOriginalTx.date !== editTx.date;\n        const results = await Promise.all((siblings || []).map((row) => {\n          const n = Math.max(current, Number(row.installment_number) || current);\n          const update: Record<string, unknown> = { ...sharedUpdate };\n          if (row.id === editTx.id) update.date = editTx.date;\n          else if (dateChanged) update.date = addMonthsIso(editTx.date, n - current);\n          return supabase.from("transactions").update(update).eq("id", row.id);\n        }));\n        const failed = results.find((result) => result.error);\n        if (failed?.error) throw failed.error;\n        toast.success("Esta parcela e as futuras foram atualizadas");\n      } else {\n        const { error } = await supabase\n          .from("transactions")\n          .update({ ...sharedUpdate, date: editTx.date })\n          .eq("id", editTx.id);\n        if (error) throw error;\n        toast.success("Parcela atualizada");\n      }\n\n      setEditScopeDialogOpen(false);\n      setShowEditDialog(false);\n      setEditOriginalTx(null);\n      if (invoiceCard) await refreshInvoiceSilently(invoiceCard);\n      else await fetchAll();\n    } catch (error: any) {\n      console.error("Error updating transaction:", error);\n      toast.error("Erro ao atualizar transação");\n    } finally {\n      setIsSavingEdit(false);\n    }\n  };\n\n  const saveEditTx = async () => {\n    if (!editTx) return;\n    const current = Math.max(1, Number(editTx.installment_number) || 1);\n    const total = Math.max(1, Number(editTx.total_installments) || 1);\n    if (editTx.installment_group_id && total > 1 && current < total) {\n      setEditScopeDialogOpen(true);\n      return;\n    }\n    await performSaveEditTx("single");\n  };\n'''
if old not in s:
    raise SystemExit('save editor anchor not found')
s = s.replace(old, new, 1)

ui_anchor = '''      {/* Delete Dialog */}\n      <Dialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>\n'''
ui = '''      <AlertDialog open={editScopeDialogOpen} onOpenChange={(open) => { if (!isSavingEdit) setEditScopeDialogOpen(open); }}>\n        <AlertDialogContent className="max-w-[calc(100vw-2rem)] sm:max-w-sm mx-auto rounded-2xl">\n          <AlertDialogHeader>\n            <AlertDialogTitle>Aplicar alteração no parcelamento?</AlertDialogTitle>\n            <AlertDialogDescription>\n              {editTx && (\n                <>\n                  Esta compra está na parcela <strong>{editTx.installment_number}/{editTx.total_installments}</strong>.\n                  Escolha se a correção vale somente para esta parcela ou também para as próximas.\n                </>\n              )}\n            </AlertDialogDescription>\n          </AlertDialogHeader>\n          <AlertDialogFooter className="gap-2 sm:gap-2">\n            <AlertDialogCancel disabled={isSavingEdit}>Voltar</AlertDialogCancel>\n            <Button\n              type="button"\n              variant="outline"\n              disabled={isSavingEdit}\n              onClick={() => void performSaveEditTx("single")}\n            >\n              Só esta parcela\n            </Button>\n            <AlertDialogAction\n              disabled={isSavingEdit}\n              onClick={(e) => {\n                e.preventDefault();\n                void performSaveEditTx("future");\n              }}\n            >\n              {isSavingEdit ? <Loader2 className="h-4 w-4 animate-spin" /> : "Esta e as futuras"}\n            </AlertDialogAction>\n          </AlertDialogFooter>\n        </AlertDialogContent>\n      </AlertDialog>\n\n      {/* Delete Dialog */}\n      <Dialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>\n'''
if ui_anchor not in s:
    raise SystemExit('scope UI anchor not found')
s = s.replace(ui_anchor, ui, 1)

p.write_text(s)

# Regression guard
Path('src/tests/cards-invoice-edit-future-scope.test.ts').write_text('''import { describe, expect, it } from "vitest";\nimport { readFileSync } from "node:fs";\n\nconst source = readFileSync(new URL("../routes/cards.tsx", import.meta.url), "utf8");\n\ndescribe("invoice installment edit scope", () => {\n  it("asks whether an installment edit applies to future installments", () => {\n    expect(source).toContain("Aplicar alteração no parcelamento?");\n    expect(source).toContain("Só esta parcela");\n    expect(source).toContain("Esta e as futuras");\n  });\n\n  it("updates only installments from the current one forward", () => {\n    expect(source).toContain('.gte("installment_number", current)');\n    expect(source).toContain('addMonthsIso(editTx.date, n - current)');\n    expect(source).toContain('performSaveEditTx("future")');\n  });\n});\n''')
print('invoice future edit scope patch prepared')
