/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'
import { Route as OrcametasRouteImport } from './routes/orcametas'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksReconciliationDailyRouteImport } from './routes/api/public/hooks/reconciliation-daily'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcametasRoute = OrcametasRouteImport.update({
  id: '/orcametas',
  path: '/orcametas',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksReconciliationDailyRoute =
  ApiPublicHooksReconciliationDailyRouteImport.update({
    id: '/api/public/hooks/reconciliation-daily',
    path: '/api/public/hooks/reconciliation-daily',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/cards': typeof CardsRoute
  '/categories': typeof CategoriesRoute
  '/chat': typeof ChatRoute
  '/goals': typeof GoalsRoute
  '/insights': typeof InsightsRoute
  '/invest': typeof InvestRoute
  '/orcametas': typeof OrcametasRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reminders': typeof RemindersRoute
  '/shop': typeof ShopRoute
  '/transactions': typeof TransactionsRoute
  '/api/public/hooks/reconciliation-daily': typeof ApiPublicHooksReconciliationDailyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/cards': typeof CardsRoute
  '/categories': typeof CategoriesRoute
  '/chat': typeof ChatRoute
  '/goals': typeof GoalsRoute
  '/insights': typeof InsightsRoute
  '/invest': typeof InvestRoute
  '/orcametas': typeof OrcametasRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reminders': typeof RemindersRoute
  '/shop': typeof ShopRoute
  '/transactions': typeof TransactionsRoute
  '/api/public/hooks/reconciliation-daily': typeof ApiPublicHooksReconciliationDailyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/cards': typeof CardsRoute
  '/categories': typeof CategoriesRoute
  '/chat': typeof ChatRoute
  '/goals': typeof GoalsRoute
  '/insights': typeof InsightsRoute
  '/invest': typeof InvestRoute
  '/orcametas': typeof OrcametasRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reminders': typeof RemindersRoute
  '/shop': typeof ShopRoute
  '/transactions': typeof TransactionsRoute
  '/api/public/hooks/reconciliation-daily': typeof ApiPublicHooksReconciliationDailyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/auth'
    | '/budget'
    | '/cards'
    | '/categories'
    | '/chat'
    | '/goals'
    | '/insights'
    | '/invest'
    | '/orcametas'
    | '/reconciliation'
    | '/reminders'
    | '/shop'
    | '/transactions'
    | '/api/public/hooks/reconciliation-daily'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/auth'
    | '/budget'
    | '/cards'
    | '/categories'
    | '/chat'
    | '/goals'
    | '/insights'
    | '/invest'
    | '/orcametas'
    | '/reconciliation'
    | '/reminders'
    | '/shop'
    | '/transactions'
    | '/api/public/hooks/reconciliation-daily'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/auth'
    | '/budget'
    | '/cards'
    | '/categories'
    | '/chat'
    | '/goals'
    | '/insights'
    | '/invest'
    | '/orcametas'
    | '/reconciliation'
    | '/reminders'
    | '/shop'
    | '/transactions'
    | '/api/public/hooks/reconciliation-daily'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AuthRoute: typeof AuthRoute
  BudgetRoute: typeof BudgetRoute
  CardsRoute: typeof CardsRoute
  CategoriesRoute: typeof CategoriesRoute
  ChatRoute: typeof ChatRoute
  GoalsRoute: typeof GoalsRoute
  InsightsRoute: typeof InsightsRoute
  InvestRoute: typeof InvestRoute
  OrcametasRoute: typeof OrcametasRoute
  ReconciliationRoute: typeof ReconciliationRoute
  RemindersRoute: typeof RemindersRoute
  ShopRoute: typeof ShopRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiPublicHooksReconciliationDailyRoute: typeof ApiPublicHooksReconciliationDailyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcametas': {
      id: '/orcametas'
      path: '/orcametas'
      fullPath: '/orcametas'
      preLoaderRoute: typeof OrcametasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reconciliation-daily': {
      id: '/api/public/hooks/reconciliation-daily'
      path: '/api/public/hooks/reconciliation-daily'
      fullPath: '/api/public/hooks/reconciliation-daily'
      preLoaderRoute: typeof ApiPublicHooksReconciliationDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AuthRoute: AuthRoute,
  BudgetRoute: BudgetRoute,
  CardsRoute: CardsRoute,
  CategoriesRoute: CategoriesRoute,
  ChatRoute: ChatRoute,
  GoalsRoute: GoalsRoute,
  InsightsRoute: InsightsRoute,
  InvestRoute: InvestRoute,
  OrcametasRoute: OrcametasRoute,
  ReconciliationRoute: ReconciliationRoute,
  RemindersRoute: RemindersRoute,
  ShopRoute: ShopRoute,
  TransactionsRoute: TransactionsRoute,
  ApiPublicHooksReconciliationDailyRoute:
    ApiPublicHooksReconciliationDailyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
