// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'
import { supabase as browserSupabase } from './client'



export const requireSupabaseAuth = createMiddleware({ type: 'function' })
  .client(async ({ next }) => {
    // Supabase persists the browser session in localStorage. TanStack Start
    // server-function requests do not automatically include that JWT, so forward
    // the current access token explicitly to the same-origin RPC request.
    const { data: { session }, error } = await browserSupabase.auth.getSession();

    if (error || !session?.access_token) {
      throw new Error('Unauthorized: No active Supabase session');
    }

    return next({
      headers: {
        Authorization: `Bearer ${session.access_token}`,
      },
    });
  })
  .server(async ({ next }) => {
    // Vercel currently exposes the public Supabase configuration with VITE_
    // prefixes because the browser also needs these values. Accept both the
    // server-only and public-prefixed names; the publishable key is not a secret.
    const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      console.error('requireSupabaseAuth missing Supabase server configuration');
      throw new Response('Server authentication unavailable', { status: 500 });
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Response('Unauthorized', { status: 401 });
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Response('Unauthorized', { status: 401 });
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Response('Unauthorized', { status: 401 });
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Response('Unauthorized', { status: 401 });
    }

    const supabase = createClient<Database>(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    // getUser validates the token against Supabase Auth instead of relying only
    // on local JWT claims. This rejects deleted/disabled users as soon as Auth
    // stops accepting their session.
    const { data, error } = await supabase.auth.getUser(token);
    if (error || !data?.user?.id) {
      if (error) console.warn('requireSupabaseAuth rejected session', error.message);
      throw new Response('Unauthorized', { status: 401 });
    }

    return next({
      context: {
        supabase,
        userId: data.user.id,
        user: data.user,
      },
    });
  })
